name: Deploy

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build for production
      run: npm run build
      env:
        NODE_ENV: production

    - name: Upload production build
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 90

    # Uncomment and configure when you have a deployment target
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download production build
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}